# FIXME-BLOCKER(Krey): Should be adapted to use `COPY` from container to container once upstream implements it, currently using a volume that is provided to relevant containers to share the content (https://github.com/docker/compose/issues/5523#issuecomment-774392560)

###! Universal `docker-compose.yml` file intended to be used as a reference for configuration and development.

version: "3"

services:
  gitea-service:
    container_name: gitea-service
    build:
      context: .
      dockerfile: docker/dockerfiles/gitea.Dockerfile
    ports:
      - "3000:3000"
      - "33629:22"
    #depends_on:
  #   - mysql-database
  # gitea-mysql-database:
  #   container_name: gitea-database
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=gitea
  #     - MYSQL_USER=gitea
  #     - MYSQL_PASSWORD=gitea
  #     - MYSQL_DATABASE=gitea
  #   volumes:
  #     - ./mysql:/var/lib/mysql