# FIXME-BLOCKER(Krey): Should be adapted to use `COPY` from container to container once upstream implements it, currently using a volume that is provided to relevant containers to share the content (https://github.com/docker/compose/issues/5523#issuecomment-774392560)

###! Universal `docker-compose.yml` file intended to be used as a reference for configuration and development.

version: "3"

services:
  build-env:
    container_name: build-env
    build:
      context: .
      dockerfile: docker/dockerfiles/build-env.Dockerfile
    volumes:
      - "gitea-common:/mnt/docker-hack"
    command: |
      make clean-all build install
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 100M
  gitea-service:
    container_name: gitea-service
    build:
      context: .
      dockerfile: docker/dockerfiles/gitea.Dockerfile
    volumes:
      - "./docker/files/confdir/gitea:/etc/gitea:rw"
      - "gitea-common:/mnt/docker-hack:rw"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 100M
    ports:
      - "3000:3000"
      - "33629:22"
    depends_on:
      - build-env
  #   - mysql-database
  # gitea-mysql-database:
  #   container_name: gitea-database
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=gitea
  #     - MYSQL_USER=gitea
  #     - MYSQL_PASSWORD=gitea
  #     - MYSQL_DATABASE=gitea
  #   volumes:
  #     - ./mysql:/var/lib/mysql
volumes:
  gitea-srcdir:
    driver: local
  gitea-common:
    driver: local